version: "3.1"
services:
  myapp:
    build: .
    image: karimmorel/degustimer
    environment:
      - MYSQL_USER_NAME=degustadmin
      - MYSQL_USER_DB=degustabase
      - MYSQL_USER_PASS=degustadmin
    ports:
      - "80:80"
    volumes:
      - ".:/app"