home:
    path: /
    controller: App\Controller\HomeController::index

task.create:
    path: /task/create
    controller: App\Controller\TaskController::create

task.stop:
    path: /task/stop
    controller: App\Controller\TaskController::stop